class Note {
  final int? id;
  final String? title; // Name
  final String? content; // Phone Number
  final String? address;
  final String? fatherName;
  final String? motherName;
  final int? termStartYear;
  final int? termEndYear;
  final int? renewYear;
  final String? paymentInfo;
  final bool? documentRegistered;
  final List<int>? documentIds;
  final double? currentSecurityAmount;
  final double? annualMaintenancePaid;
  final double? partyChargePerYear;
  final DateTime? modifiedTime;
  final String? imageID;

  Note({
    this.id,
    this.title,
    this.content,
    this.address,
    this.fatherName,
    this.motherName,
    this.termStartYear,
    this.termEndYear,
    this.renewYear,
    this.paymentInfo,
    this.documentRegistered,
    this.documentIds,
    this.currentSecurityAmount,
    this.annualMaintenancePaid,
    this.partyChargePerYear,
    this.modifiedTime,
    this.imageID,
  });
}

List<Note> sampleNotes = [
  Note(
    id: 0,
    title: 'Ananya',
    content: '98765 43210',
    address: '123 MG Road, Mumbai',
    fatherName: 'Ramesh Sharma',
    motherName: 'Sunita Sharma',
    termStartYear: 2020,
    termEndYear: 2025,
    renewYear: 2026,
    paymentInfo: 'Paid via UPI',
    documentRegistered: true,
    documentIds: [101, 102, 103],
    currentSecurityAmount: 5000,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 21, 10, 30),
    imageID: 'img_001',
  ),
  Note(
    id: 1,
    title: 'Priya',
    content: '87654 32109',
    address: '456 Connaught Place, Delhi',
    fatherName: 'Vikram Mehta',
    motherName: 'Neeta Mehta',
    termStartYear: 2019,
    termEndYear: 2024,
    renewYear: 2025,
    paymentInfo: 'Paid via Net Banking',
    documentRegistered: true,
    documentIds: [104, 105],
    currentSecurityAmount: 7000,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 20, 9, 15),
    imageID: 'img_002',
  ),
  Note(
    id: 2,
    title: 'Meera',
    content: '76543 21098',
    address: '789 Brigade Road, Bangalore',
    fatherName: 'Rajiv Kapoor',
    motherName: 'Anjali Kapoor',
    termStartYear: 2021,
    termEndYear: 2026,
    renewYear: 2027,
    paymentInfo: 'Paid via Credit Card',
    documentRegistered: false,
    documentIds: [],
    currentSecurityAmount: 3000,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 19, 14, 45),
    imageID: 'img_003',
  ),
  Note(
    id: 3,
    title: 'Aisha',
    content: '65432 10987',
    address: '567 Park Street, Kolkata',
    fatherName: 'Amit Verma',
    motherName: 'Jyoti Verma',
    termStartYear: 2022,
    termEndYear: 2027,
    renewYear: 2028,
    paymentInfo: 'Paid via Cash',
    documentRegistered: true,
    documentIds: [106, 107, 108],
    currentSecurityAmount: 6000,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 18, 11, 20),
    imageID: 'img_004',
  ),
  Note(
    id: 4,
    title: 'Sanya',
    content: '54321 09876',
    address: '890 Marine Drive, Mumbai',
    fatherName: 'Dinesh Malhotra',
    motherName: 'Rekha Malhotra',
    termStartYear: 2018,
    termEndYear: 2023,
    renewYear: 2024,
    paymentInfo: 'Paid via Debit Card',
    documentRegistered: false,
    documentIds: [],
    currentSecurityAmount: 4000,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 17, 13, 55),
    imageID: 'img_005',
  ),
  Note(
    id: 5,
    title: 'Kavya',
    content: '43210 98765',
    address: '12 Residency Road, Chennai',
    fatherName: 'Suresh Iyer',
    motherName: 'Lakshmi Iyer',
    termStartYear: 2023,
    termEndYear: 2028,
    renewYear: 2029,
    paymentInfo: 'Paid via UPI',
    documentRegistered: true,
    documentIds: [109, 110],
    currentSecurityAmount: 8000,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 16, 16, 10),
    imageID: 'img_006',
  ),
  Note(
    id: 6,
    title: 'Riya',
    content: '32109 87654',
    address: '33 MG Road, Pune',
    fatherName: 'Manoj Desai',
    motherName: 'Pooja Desai',
    termStartYear: 2017,
    termEndYear: 2022,
    renewYear: 2023,
    paymentInfo: 'Paid via Bank Transfer',
    documentRegistered: true,
    documentIds: [111, 112],
    currentSecurityAmount: 3500,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 15, 10, 40),
    imageID: 'img_007',
  ),
  Note(
    id: 7,
    title: 'Neha',
    content: '21098 76543',
    address: '101 Indiranagar, Bangalore',
    fatherName: 'Sameer Joshi',
    motherName: 'Alka Joshi',
    termStartYear: 2024,
    termEndYear: 2029,
    renewYear: 2030,
    paymentInfo: 'Paid via Credit Card',
    documentRegistered: false,
    documentIds: [],
    currentSecurityAmount: 4500,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 14, 17, 25),
    imageID: 'img_008',
  ),
  Note(
    id: 8,
    title: 'Ishita',
    content: '10987 65432',
    address: '75 Gariahat Road, Kolkata',
    fatherName: 'Naveen Ghosh',
    motherName: 'Madhuri Ghosh',
    termStartYear: 2025,
    termEndYear: 2030,
    renewYear: 2031,
    paymentInfo: 'Paid via Online Wallet',
    documentRegistered: true,
    documentIds: [113],
    currentSecurityAmount: 9000,
    annualMaintenancePaid: 1000,
    partyChargePerYear: 500,
    modifiedTime: DateTime(2024, 3, 13, 12, 50),
    imageID: 'img_009',
  ),
];
