// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqe3oliRy8g1fvGgV7JldkAdEee2ld9f8',
    appId: '1:783237653876:web:ff9f704e1ad081aa83f821',
    messagingSenderId: '783237653876',
    projectId: 'ayaan-hostel',
    authDomain: 'ayaan-hostel.firebaseapp.com',
    storageBucket: 'ayaan-hostel.firebasestorage.app',
    measurementId: 'G-KKQ75806VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0KCYBja0KrLz1eubm4NqZn7EFA6LQWEI',
    appId: '1:783237653876:android:1da7fb81e878fed483f821',
    messagingSenderId: '783237653876',
    projectId: 'ayaan-hostel',
    storageBucket: 'ayaan-hostel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDe5DAgnenB3luCgbfkUEXB5mijN3-mlE',
    appId: '1:783237653876:ios:b168c99d08b2fd5f83f821',
    messagingSenderId: '783237653876',
    projectId: 'ayaan-hostel',
    storageBucket: 'ayaan-hostel.firebasestorage.app',
    iosBundleId: 'com.example.anayahostelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDe5DAgnenB3luCgbfkUEXB5mijN3-mlE',
    appId: '1:783237653876:ios:b168c99d08b2fd5f83f821',
    messagingSenderId: '783237653876',
    projectId: 'ayaan-hostel',
    storageBucket: 'ayaan-hostel.firebasestorage.app',
    iosBundleId: 'com.example.anayahostelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqe3oliRy8g1fvGgV7JldkAdEee2ld9f8',
    appId: '1:783237653876:web:502d70b8231d926283f821',
    messagingSenderId: '783237653876',
    projectId: 'ayaan-hostel',
    authDomain: 'ayaan-hostel.firebaseapp.com',
    storageBucket: 'ayaan-hostel.firebasestorage.app',
    measurementId: 'G-XDH5D6GW6S',
  );
}
